services:
  next-js:
    image: node:22-alpine
    command: npm run dev --turbo
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      # Neon development database; connection string comes from .env file
      - DATABASE_URL=${DATABASE_URL}

volumes:
  node_modules:
