--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2 (Debian 17.2-1.pgdg120+1)
-- Dumped by pg_dump version 17.2 (Debian 17.2-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: drizzle; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA drizzle;


ALTER SCHEMA drizzle OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: __drizzle_migrations; Type: TABLE; Schema: drizzle; Owner: postgres
--

CREATE TABLE drizzle.__drizzle_migrations (
    id integer NOT NULL,
    hash text NOT NULL,
    created_at bigint
);


ALTER TABLE drizzle.__drizzle_migrations OWNER TO postgres;

--
-- Name: __drizzle_migrations_id_seq; Type: SEQUENCE; Schema: drizzle; Owner: postgres
--

CREATE SEQUENCE drizzle.__drizzle_migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE drizzle.__drizzle_migrations_id_seq OWNER TO postgres;

--
-- Name: __drizzle_migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: drizzle; Owner: postgres
--

ALTER SEQUENCE drizzle.__drizzle_migrations_id_seq OWNED BY drizzle.__drizzle_migrations.id;


--
-- Name: alexs-archive_account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."alexs-archive_account" (
    user_id character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    provider character varying(255) NOT NULL,
    provider_account_id character varying(255) NOT NULL,
    refresh_token text,
    access_token text,
    expires_at integer,
    token_type character varying(255),
    scope character varying(255),
    id_token text,
    session_state character varying(255)
);


ALTER TABLE public."alexs-archive_account" OWNER TO postgres;

--
-- Name: alexs-archive_book; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."alexs-archive_book" (
    id integer NOT NULL,
    title text NOT NULL,
    series text,
    series_num integer,
    author text NOT NULL,
    page_count integer NOT NULL,
    published_date character varying(255) NOT NULL,
    image_url character varying(255) NOT NULL,
    good_reads_url character varying(255) NOT NULL,
    created_by character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone
);


ALTER TABLE public."alexs-archive_book" OWNER TO postgres;

--
-- Name: alexs-archive_book_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."alexs-archive_book" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."alexs-archive_book_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alexs-archive_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."alexs-archive_session" (
    session_token character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL,
    expires timestamp with time zone NOT NULL
);


ALTER TABLE public."alexs-archive_session" OWNER TO postgres;

--
-- Name: alexs-archive_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."alexs-archive_user" (
    id character varying(255) NOT NULL,
    name character varying(255),
    email character varying(255) NOT NULL,
    email_verified timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    image character varying(255)
);


ALTER TABLE public."alexs-archive_user" OWNER TO postgres;

--
-- Name: alexs-archive_verification_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."alexs-archive_verification_token" (
    identifier character varying(255) NOT NULL,
    token character varying(255) NOT NULL,
    expires timestamp with time zone NOT NULL
);


ALTER TABLE public."alexs-archive_verification_token" OWNER TO postgres;

--
-- Name: __drizzle_migrations id; Type: DEFAULT; Schema: drizzle; Owner: postgres
--

ALTER TABLE ONLY drizzle.__drizzle_migrations ALTER COLUMN id SET DEFAULT nextval('drizzle.__drizzle_migrations_id_seq'::regclass);


--
-- Data for Name: __drizzle_migrations; Type: TABLE DATA; Schema: drizzle; Owner: postgres
--

COPY drizzle.__drizzle_migrations (id, hash, created_at) FROM stdin;
1	dbc346f0788f1065a01ce07661f39f9975a8aceb95c46bddd0df01b57cf6b137	1740156306663
\.


--
-- Data for Name: alexs-archive_account; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."alexs-archive_account" (user_id, type, provider, provider_account_id, refresh_token, access_token, expires_at, token_type, scope, id_token, session_state) FROM stdin;
\.


--
-- Data for Name: alexs-archive_book; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."alexs-archive_book" (id, title, series, series_num, author, page_count, published_date, image_url, good_reads_url, created_by, created_at, updated_at) FROM stdin;
1	A Court of Thorns and Roses	\N	\N	Sarah J. Maas	419	June 2, 2020	https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1620324329i/50659467.jpg	https://www.goodreads.com/book/show/50659467-a-court-of-thorns-and-roses	1	2025-03-05 20:59:53.443877+00	\N
2	Fourth Wing	The Empyrean	3	Rebecca Yarros	517	May 2, 2023	https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1701980900i/61431922.jpg	https://www.goodreads.com/book/show/61431922-fourth-wing	1	2025-03-05 21:02:33.818995+00	\N
\.


--
-- Data for Name: alexs-archive_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."alexs-archive_session" (session_token, user_id, expires) FROM stdin;
\.


--
-- Data for Name: alexs-archive_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."alexs-archive_user" (id, name, email, email_verified, image) FROM stdin;
1	Alex	alex@dobsondev.com	2025-03-05 20:58:07.198471+00	\N
\.


--
-- Data for Name: alexs-archive_verification_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."alexs-archive_verification_token" (identifier, token, expires) FROM stdin;
\.


--
-- Name: __drizzle_migrations_id_seq; Type: SEQUENCE SET; Schema: drizzle; Owner: postgres
--

SELECT pg_catalog.setval('drizzle.__drizzle_migrations_id_seq', 1, true);


--
-- Name: alexs-archive_book_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."alexs-archive_book_id_seq"', 1, false);


--
-- Name: __drizzle_migrations __drizzle_migrations_pkey; Type: CONSTRAINT; Schema: drizzle; Owner: postgres
--

ALTER TABLE ONLY drizzle.__drizzle_migrations
    ADD CONSTRAINT __drizzle_migrations_pkey PRIMARY KEY (id);


--
-- Name: alexs-archive_account alexs-archive_account_provider_provider_account_id_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."alexs-archive_account"
    ADD CONSTRAINT "alexs-archive_account_provider_provider_account_id_pk" PRIMARY KEY (provider, provider_account_id);


--
-- Name: alexs-archive_book alexs-archive_book_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."alexs-archive_book"
    ADD CONSTRAINT "alexs-archive_book_pkey" PRIMARY KEY (id);


--
-- Name: alexs-archive_session alexs-archive_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."alexs-archive_session"
    ADD CONSTRAINT "alexs-archive_session_pkey" PRIMARY KEY (session_token);


--
-- Name: alexs-archive_user alexs-archive_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."alexs-archive_user"
    ADD CONSTRAINT "alexs-archive_user_pkey" PRIMARY KEY (id);


--
-- Name: alexs-archive_verification_token alexs-archive_verification_token_identifier_token_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."alexs-archive_verification_token"
    ADD CONSTRAINT "alexs-archive_verification_token_identifier_token_pk" PRIMARY KEY (identifier, token);


--
-- Name: account_user_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_user_id_idx ON public."alexs-archive_account" USING btree (user_id);


--
-- Name: session_user_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX session_user_id_idx ON public."alexs-archive_session" USING btree (user_id);


--
-- Name: alexs-archive_account alexs-archive_account_user_id_alexs-archive_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."alexs-archive_account"
    ADD CONSTRAINT "alexs-archive_account_user_id_alexs-archive_user_id_fk" FOREIGN KEY (user_id) REFERENCES public."alexs-archive_user"(id);


--
-- Name: alexs-archive_book alexs-archive_book_created_by_alexs-archive_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."alexs-archive_book"
    ADD CONSTRAINT "alexs-archive_book_created_by_alexs-archive_user_id_fk" FOREIGN KEY (created_by) REFERENCES public."alexs-archive_user"(id);


--
-- Name: alexs-archive_session alexs-archive_session_user_id_alexs-archive_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."alexs-archive_session"
    ADD CONSTRAINT "alexs-archive_session_user_id_alexs-archive_user_id_fk" FOREIGN KEY (user_id) REFERENCES public."alexs-archive_user"(id);


--
-- PostgreSQL database dump complete
--

